 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     

     steps:
       - checkout
       - run: dotnet build
title: Freecause
description: I AM SMART ( MAN )
google_analytics: 
show_downloads: false
theme: jekyll-theme-slate
gems:
  - jekyll-mentions
